Prze³om, który dotkn±³ naszego kraju i przemiany, które mu towarzyszy³y nie ominê³y równie¿ ZHP. Chêæ powrotu do szlachetnych tradycji harcerstwa przedwojennego spowodowa³y powstanie KIHAM (Krêgi Instruktorów Harcerskich im. Andrzeja Ma³kowskiego). Stanowi³o to swoiste odrodzenie, tchnê³o nowego ducha pracy w dru¿yny. Poznawano historiê, zdobywano tradycyjne stopnie, sprawno¶ci, odkrywano techniki harcerskie, na nowo zaciekawia³a pionierka i samarytanka. Wszystko to by³o jednak oficjalnie zakazane, ale fascynacja i chêæ harcerskiego ducha by³a silniejsza. Przemiany dotknê³y równie¿ mundurów. Pojawi³y siê nowe elementy militarne, guziki, lilijki i rogatywki. ¦piewano coraz czê¶ciej przedwojenne piosenki. Dru¿yny nale¿±ce do KIHAMU uczestniczy³y w Toporach. By³y to biwaki integruj±ce i sprawdzaj±ce zdobyt± wiedzê. Pierwszy Topór odby³ siê w 1981r w Lublinie, na skraju Puszczy Rzepiñskiej, nastêpny rok pó¼niej w Bytnicy. Uczestnicy na pami±tkê otrzymywali baretkê noszona na kieszeni munduru. Tego samego roku 45 KDH "WIGRY" wraz z 9 DSH "Dukt" pojecha³a na Tajny Zlot KIHAM-u na Jasn± Górê do Czêstochowy. Zastanawiano siê ju¿ wtedy powa¿nie nad odej¶ciem z ZHP i utworzeniem odrêbnej organizacji. Wynikiem jego by³a decyzja, ¿e jednak Zwi±zek Dru¿yn KIHAM pozostanie w ZHP, próbuj±c od ¶rodka reformowaæ te organizacjê. ¦rodowisko w tamtym czasie w Zielonej Górze tworzy³y 3 dru¿yny- 9 DSH "DUKT", 45 KDH " WIGRY", oraz 31 DH "WESO£A WIARA". Ich dru¿ynowymi wówczas byli w kolejno¶ci dru¿yn Jasiu (Jan Sawicki) , Cebul (S³awomir Cebula) i Benek (Bernard Lewandowski). Przewodnicz±cym Krêgu by³ phm Adam Markowski. W ?83 KIHAM przekszta³ci³ siê w Ruch P³askiego Wêz³a, którego symbolem by³a lilijka przewi±zana bia³o-czerwonym p³askim wêz³em. Poszerzono wtedy sk³ad o 30 DH Orlêta oraz 64 DH Puchacze. Ich wodzami byli Jacek Zuchantke i Aleksander Kieæ.<br/>
Odej¶cie z ZHP i wst±pienie do ZHR nast±pi³o w momencie , kiedy wodzami byli Gamma  (Katarzyna Grochowska) i £ysy (Jacek Kanclerz) z 45 KDH Wigry, Banaczek (Jaros³aw Skorulski), Dziadek (Robert Górowski) i Balbina z 9 DSH Dukt a z dru¿yn 30 DH Orlêta- Tuptu¶ (Anna Cierulkiewicz-Traczyk), Mariusz Grabowy, 31- Budzik (Pawe³ Kochañski). Dukt jednak nie wst±pi³ tak od razu do ZHR wraz ze wszystkimi dru¿ynami. Dru¿ynowy trze¼wiej patrzy³ na t± sytuacjê, d³u¿ej podejmowa³ decyzjê. Wiosna ?90 Dukt jako ostatnia dru¿yna wyst±pili z ZHP. Krok ten by³ naturaln± konsekwencj± ruchu ca³ego ¶rodowiska w zwi±zku z sytuacj± wokó³ obrad Okr±g³ego Sto³u oraz pielgrzymk± do Polski Papie¿a Jana Paw³a II. Dla nas wtedy by³ to radosny moment, kiedy nie musieli¶my ju¿ pos³ugiwaæ siê dwiema ksi±¿eczkami harcerskimi, nie musieli¶my siê ju¿ ukrywaæ z naszym Przyrzeczeniem i Prawem Harcerskim. Wrócili¶my do tradycyjnego systemu stopni i sprawno¶ci harcerskich, tradycyjnych metod pracy . Mogli¶my dzia³aæ bez strachu przed konsekwencjami i szykanami ze strony w³adz ZHP. Dla wielu dru¿yn by³ to krok bardzo ryzykowny oraz okupiony dotkliwymi stratami.<br/>
<br/>
Obecnie w Zielonej Górze stoi pomnik po¶wiêcony harcerzom ZHR. Jego historia równie¿ jest ciekawa, bowiem szukano odpowiedniego kamienia do tego celu. Nie by³o to jednak ³atwe. Termin nieub³agalnie mija³, ju¿ nie mieli nadzieji... Pewnego dnia na budowie przed domem Jaros³aw Skorulski zwyczajnie siê na niego natkn±³. Za¶ tablica widniej±ca na kamieniu by³a wytapiana w specjalnie przeznaczonym to tego piecu w dwóch czê¶ciach.<br/>
<br/>
<div style="text-align: right; font-size: small; font-style: italic;">
    Na spacjalne zlecenie<br/>
    Darii Werykowicz aka "Poposz"<br/>
    <br/>
    wysma¿y³ i nieco przypiek³<br />
    <?= getWebmaster(); ?>, <? echo date("d.m.Y", filemtime($page)) ?>
</div>